### ISSUE TITLE
[Bug]: The height of the icon button reduces its size in the app, but it appears correct in the preview.

### ISSUE THREAD

**Issue by vsnshanmuganathan** [lowcoder-org/lowcoder#1313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

it looks like below
![Screenshot 2024-11-17 at 3 11 01 PM](https://github.com/user-attachments/assets/adc8a67b-9d9c-4085-b56d-b04ae3f6a515)

### Expected Behavior

It should looks like this,
![Screenshot 2024-11-17 at 3 10 51 PM](https://github.com/user-attachments/assets/6f3c20be-884b-4a3e-9ff1-8fa86d0b8918)

### Steps to reproduce

Drag the Icon Button component,
change the Margin to zero, 
It looks fine in the preview, but it becomes smaller when published.

### Environment

lowcoder v2.4.12 on docker

**Comment by FalkWolsky** [comment]
<img width="348" alt="Screenshot 2024-11-18 at 18 21 41" src="https://github.com/user-attachments/assets/1794ac11-1bc8-4d54-98f0-f28817663531">

We checked and could not find a size-change as a unwanted behaviour. 
The size of the button is controlled by "AutoHeight" or "Fixed". 
Only for AutoHeight the Aspect Ratio is used and make sure that the button will not shrink down.

If you think that we misunderstood your issue, please re-open the issue here.

**Comment by vsnshanmuganathan** [comment]
i found it's not because of margin, it's because of borderWidth,
if borderWidth is 0 then button shrinks, try with below json file
[test.json](https://github.com/user-attachments/files/17906303/test.json)
