### ISSUE TITLE
[Bug]: Allowlist missing

### ISSUE THREAD

**Issue by Charuru** [lowcoder-org/lowcoder#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Allowlist
Add the following IP addresses of Lowcoder to your data source allowlist when needed.

What following IP addresses?

### Expected Behavior

See ip addresses

### Steps to reproduce

Try to add a datasource

### Environment

lowcoder.cloud

**Comment by ds2-jetten** [comment]
I was looking for this as well. 
The allow list link in the docs ([data-source-basics.md](https://github.com/lowcoder-org/lowcoder/blob/main/docs/data-sources/data-source-basics.md#connect-to-a-new-data-source)) points to a missing markdown document: 
https://github.com/lowcoder-org/lowcoder/blob/main/docs/data-sources/configure-ip-allowlists.md

**Comment by Charuru** [comment]
> I was looking for this as well. The allow list link in the docs ([data-source-basics.md](https://github.com/lowcoder-org/lowcoder/blob/main/docs/data-sources/data-source-basics.md#connect-to-a-new-data-source)) points to a missing markdown document: https://github.com/lowcoder-org/lowcoder/blob/main/docs/data-sources/configure-ip-allowlists.md

Looks like the project's not in a good state unfortunately, 3 business days without a reply on something this show stopping. RIP.

**Comment by ds2-jetten** [comment]
Yeah, this seems like a really easy win too.

**Comment by FalkWolsky** [comment]
Let us briefly ask, which IPs you want to allow. I mean from which direction.
There are IP Addressed from the App in the cloud installation, which needs to be whitelisted when you have datasources behind firewalls. If you have a self-installation, then normally there is no such thing as a whitelist needed, since from Lowcoder on, any reachable IP is ... reachable.

Please give an indication what exactly you mean.

**Comment by FalkWolsky** [comment]
Between, we are everything else than dead, since we use the summer intensely to make a huge step forward and offer much-requested features. Please excuse, us when we maybe over-focused on this and have forgotten a bit about the communication side.

**Comment by Charuru** [comment]
Great to hear that you're not dead.

I'm looking for the lowcode.cloud's IP address so I can allow you from my database's firewall.

**Comment by FalkWolsky** [comment]
Now I understand. And - no, it is not a bug.

https://docs.lowcoder.cloud/lowcoder-documentation/connect-your-data/data-source-basics/configure-ip-allowlists

Please find this info in our documentation. The place you did look for was in the Github, which points to the old Openblocks Documentation. However, there was so much not described, that we already since weeks work on a better docu.

**Comment by Charuru** [comment]
<img width="1285" alt="Screen Shot 2023-08-20 at 11 48 14 AM" src="https://github.com/lowcoder-org/lowcoder/assets/214436/af88496e-a5b1-48dc-a608-cf3c28cf544d">

Thanks for the link, but I didn't look in the github I was just using your website.

**Comment by FalkWolsky** [comment]
Ah. Very good. We can make these IP addresses visible inside the app too.
At least we should link into the documentation.
