### ISSUE TITLE
[Bug]: When you open a link published by the Lowcoder using the iframe, the custom component can not be displayed

### ISSUE THREAD

**Issue by ganyz505** [lowcoder-org/lowcoder#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/lowcoder-org/lowcoder/assets/45992054/9d259aef-bbe6-4019-abe4-9f5690c090bc)

### Expected Behavior

![image](https://github.com/lowcoder-org/lowcoder/assets/45992054/394fd7fd-e031-4cdc-9c32-dafa380f9f40)

### Steps to reproduce

use <iframe src="xxxlowcoderURL"> and custom conponents

**Comment by FalkWolsky** [comment]
IFrames are limited for security reasons. One of the limitations is the lazy loading of JavaScript which is needed for Lowcoder. 

<img width="1063" alt="Screenshot 2023-11-11 at 09 22 36" src="https://github.com/lowcoder-org/lowcoder/assets/3671017/2e6016d5-ab94-43a7-99e2-d50b8207f35d">

Did you activate the "download" switch?

So, as I understand you want to load a Lowcoder App inside of an iFrame in a Lowcoder App?
Was the use of a Module, not a choice? Please describe to us what and why you try to solve it this way... Maybe we can find a solution.

**Comment by ganyz505** [comment]
Sorry, my description is wrong. What I want to do now is to use Lowcoder to make an application (the application uses Lowcoder's Custom Components), then publish it to get a link, and finally use the <iframe> tag in HTML to embed the application published using Lowcoder in a third-party system. The problem I have now is that when using the <iframe> tag to embed an application published by Lowcoder, the content of Custom Components in Lowcoder cannot be displayed.
![1699693051576](https://github.com/lowcoder-org/lowcoder/assets/45992054/99d197a5-927d-44ff-a250-13924437abc8)

**Comment by FalkWolsky** [comment]
Now we understand you better. Still, you will face problems for security reasons with the iFrame. The reason is, that custom components currently need some sources from sdk.lowcoder.cloud. And this is suppressed for security reason in the iFrame.

One of the amazing capabilities of Lowcoder is the ability to embed it native in Web Applications. We wonder why you did not make use of that? (IFrame based integration is always the worse).

Please have a look here: https://docs.lowcoder.cloud/lowcoder-documentation/lowcoder-extension/native-embed-sdk
Especially the page for native embedding in HTML pages. 

Maybe this supports better what you need?

**Comment by FalkWolsky** [comment]
We closed the issue for now, as it is not directly connected to Lowcoder. But we have a takeaway and a promise. The sources, which currently need to get loaded from sdk.lowcoder.cloud will have to move into the main distribution. This would solve the issue with iFrame then too. But we strongly discourage to run Lowcoder in Iframes.

**Comment by dllnaoki** [comment]
have you solve the problem @ganyz505
