### ISSUE TITLE
[Bug]: Table Component > Sorting doesn't work

### ISSUE THREAD

**Issue by renekahr** [lowcoder-org/lowcoder#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sorting a number column:
<img width="174" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/100137712/13d4e314-4277-4c7a-9fe0-8543d053cbfb">

### Expected Behavior

Correct sorting.

### Steps to reproduce

Add a number column with different values. Try sorting.

**Comment by FalkWolsky** [comment]
We checked it and the table behavior is ok. How it can still come to this sorting at your side and how you can fix that?

Sorting belongs to Numbers, so the table column must have the "type" number. But this is only the first part.

```
{
  "id": 1,
  "sales_volume": 90,
  "discount_percentage": "55"
}
```

You see in this example, that both columns should show numbers. But in JSON notation only "sales_volume" is truly a number. "discount_percentage" is expressed as "String" Type because of the "" signs.
