### ISSUE TITLE
[Bug]: Table Component filter shows hash value for columns without a title

### ISSUE THREAD

**Issue by jnewman-eti** [lowcoder-org/lowcoder#601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/lowcoder-org/lowcoder/assets/71901978/d57a457b-82f7-49d6-9423-62f9c7455a05)

After creating a column on a table, and not giving it a title, the filter shows an id value for the column.  This gives the table an unprofessional look to the end users.

### Expected Behavior

Have a separate field for column name, and a separate field for title.  One gets displayed on the column header, the other is used for referencing in the filter.

### Steps to reproduce

Create a table
Add a custom column, but give it no title.
View the filter options, see the new column being referenced by some generated id.

**Comment by FalkWolsky** [comment]
Thank you very much for reporting this. We work currently on the table, so we can fix it too.

**Comment by FalkWolsky** [comment]
This is fixed now in a way... The reason was, that "something needed to be in place", when no title was set.
So, these hash values are created. It was therefore not really a bug. We solved it now in a way, that one can hide the header title of a column. Also, when no Title is set, the hash value is displayed as "information", that there is something in place.
