### ISSUE TITLE
[Feat]: Cutting/Pasting components preserve component name

### ISSUE THREAD

**Issue by mdpung** [lowcoder-org/lowcoder#664]
**Is your feature request related to a problem? Please describe.**
Cutting and pasting components does not preserve name of component. Thus, when copy pasting a form with many inputs have to be manually renamed to match the original so original SQL queries still reference valid components.

**Describe the solution you'd like**
Cutting and pasting components preserve names.

**Describe alternatives you've considered**

1. Manually dragging components but at the moment, physically dragging components can permanently move other components before releasing the components.
2. Manually renaming components to original names, which can easily require a lot of overhead.

**Additional context**

**Comment by FalkWolsky** [comment]
This was already talked about sometime in the past. We checked it and will not change the behavior as it would lead to errors when we would keep the names after pasting. Names must be unique and the internal engine takes care of that.

The second point in your issue is an enhancement, which we are currently working on. Next to the layer functionality we will offer several layout helper functions to reduce this negative effect.
