### ISSUE TITLE
[Feat]: Email not send successfully from smtp when register account, and there are no "forget password" and "reset password" function.

### ISSUE THREAD

**Issue by niemingzhao** [lowcoder-org/lowcoder#942]
Are there some checking methods or system logs to check the progress of smtp email sending? I deploy lowcoder service on my container vps with using all-in-one docker image, and setting env of smtp server, but it not worked - no email can receive. I made a check on docker logs, but there is nothing about email sending! SO COULD YOU HELP ME?
And I notice that on the login page, there is no "forget password" or "reset password" entries, even in personal setting page. so how can user forgotten their password to login? SO IS IT IN YOUR DEVELOPMENT PLAN?

**Comment by FalkWolsky** [comment]
Generally, the SMTP Server is only active for the Password Reset Flow.
It is triggered here: https://app.lowcoder.cloud/user/auth/forgot-password or https://<yourInstance>/user/auth/forgot-password.

At this flow the SMTP Server would try to send an eMail with a password reset link to the respective user.

So, "forget password" and "reset password" function are in place (since v2.4.0), where also the SMTP ENV Variables was introduced. For the register account, there is currently no need for an eMail - as we do not check it via the eMail link to sign up.

Please re-open the issue if you think we did misunderstood you.

**Comment by niemingzhao** [comment]
What image I used is arm64 type. So, arm64 type image hasn't reach ver.2.4.0?
